# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7491b89f947bf7aa5afb1fddab70c6e4375dfd41d41da0b1a5004e11a9ffe27a76b7524c95deb4b52cd213668c368c9184d72c7ac757048086c8f576248486f3

test:
  secret_key_base: e15d000241872579435ba32b562a19b26f6460e4f4cd69b37434f017d445db6582b552e6c2d2eb7aece71d2f3ba9a990cc9a899ac75fc3f21205bd19b817275f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
